import type { Metadata } from "next";
import { Roboto, Instrument_Sans, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";

const instrumentSansHeading = Instrument_Sans({
  subsets: ["latin"],
  variable: "--font-heading",
});

const roboto = Roboto({ subsets: ["latin"], variable: "--font-sans" });

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        "font-jakarta",
        roboto.variable,
        instrumentSansHeading.variable,
        plusJakartaSans.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <Toaster position="top-center" duration={2000} />
      </body>
    </html>
  );
}
